name: pomo
description: A simple Pomodoro timer app
version: 1.2.1+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  audioplayers: ^6.0.0
  bloc: ^8.1.3
  dio: ^5.4.3+1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  logger: ^2.2.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  window_manager: ^0.3.8

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Rubik Mono One
      fonts:
        - asset: fonts/RubikMonoOne-Regular.ttf

    - family: Lilita One
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf

    - family: Major Mono Display
      fonts:
        - asset: fonts/MajorMonoDisplay-Regular.ttf

  assets:
    - 'assets/sounds/click.aac'
    - 'assets/sounds/pop.aac'
    - 'assets/sounds/ding_dong.aac'
    - 'assets/images/pomo_logo.svg'
    - 'assets/images/pomo_logo.png'
    - 'assets/images/pomo_splash.png'
    - 'fonts/MajorMonoDisplay-Regular.ttf'
    - 'fonts/RubikMonoOne-Regular.ttf'
    - 'fonts/LilitaOne-Regular.ttf'
